"""intial create

Revision ID: 877f4edb4bea
Revises: 
Create Date: 2022-10-13 12:34:46.034760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877f4edb4bea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_author', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'about_author')
    # ### end Alembic commands ###
