"""create about author field error

Revision ID: 8aa4d063c0ab
Revises: 9c5231d55efd
Create Date: 2022-10-08 15:51:39.927164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8aa4d063c0ab'
down_revision = '9c5231d55efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=False))
    op.drop_column('users', 'about_authorr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_authorr', mysql.TEXT(), nullable=False))
    op.drop_column('users', 'about_author')
    # ### end Alembic commands ###
