"""create about author field

Revision ID: 9c5231d55efd
Revises: 56043d79756c
Create Date: 2022-10-08 15:36:25.278383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5231d55efd'
down_revision = '56043d79756c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_authorr', sa.Text(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_authorr')
    # ### end Alembic commands ###
